#!/bin/bash

STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\.php | sed 's|^api/*||'`

echo "Checking PHP Lint..."
make NO_TTY=1 php.analyze $STAGED_FILES_CMD

if [ $? != 0 ]
then
    echo "Fix the error before commit."
    exit 1
fi

if [ "$STAGED_FILES_CMD" != "" ]
then
    echo -e "\033[1;42mRunning Code Sniffer\033[0m"
    make NO_TTY=1 qa.codesniffer.fix.files $STAGED_FILES_CMD
fi

exit $?